name: Build and deploy to pages

on:
  push:
    branches:
      - develop
      - main
      - research

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update symlinks
        run: |
          rm -f ./frontend/src/data/inscriptions
          ln -s ../../../data/raw/inscriptions ./frontend/src/data/inscriptions

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        run: |
          touch ./frontend/.env
          echo DEBUG=true >> ./frontend/.env

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Test
        continue-on-error: true
        run: |
          npm run -w frontend test

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(frontend): update test results"
          file_pattern: "frontend/src/lib/prerender-errors.json frontend/test-results/*.json"

      - name: Build
        run: |
          npm run frontend:build

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./frontend/build
          github_token: ${{ secrets.GITHUB_TOKEN }}
