name: Build and deploy to pages

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        run: |
          touch .env
          echo DEBUG=true >> ./frontend/.env

      - name: Install dependencies
        run: |
          npm ci

      - name: Test
        continue-on-error: true
        run: |
          npm run -w frontend test

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(frontend): update test results"
          file_pattern: "frontend/test-results/*.json"

      - name: Build
        run: |
          npm run frontend:build

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./frontend/build
          github_token: ${{ secrets.GITHUB_TOKEN }}
